services:
  web:
    build: .
    container_name: apex_app_prod
    restart: always
    env_file:
      - .env
    environment:
      # USANDO O SEU IP REAL DA VM PARA O BANCO
      DATABASE_URL: "postgresql://vmuser114:150623@192.168.1.176:5432/apex_production"
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "true"
      FORCE_SSL: "false"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./storage:/app/storage
      - ./public/uploads:/app/public/uploads
    # Essa linha ajuda o container a enxergar o IP do host
    extra_hosts:
      - "host.docker.internal:host-gateway"
