# Usa a versão exata do seu Ruby
FROM ruby:3.4.4-slim

# Instala dependências do sistema para Postgres e Processamento de Imagem (libvips)
RUN apt-get update -qq && apt-get install -y \
    build-essential \
    libpq-dev \
    libvips \
    curl \
    pkg-config

# Define o diretório de trabalho
WORKDIR /app

# Variáveis para produção
ENV RAILS_ENV=production \
    BUNDLE_WITHOUT="development test" \
    RAILS_SERVE_STATIC_FILES=true \
    RAILS_LOG_TO_STDOUT=true

# Copia e instala as Gems
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copia o código do projeto
COPY . .

# Expõe a porta 3000
EXPOSE 3000

# Comando para limpar o PID do server e iniciar o Rails
CMD ["bash", "-c", "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"]
