services:
  db:
    image: postgres:16
    container_name: apex_db_prod
    restart: always
    environment:
      POSTGRES_USER: vmuser114
      POSTGRES_PASSWORD: "150623"
      POSTGRES_DB: apex_production
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432" # Removido o 127.0.0.1

volumes:
  pgdata:
