default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default

test:
  <<: *default
  database: apex_test

production:
  primary:
    <<: *default

  cache:
    <<: *default

  queue:
    <<: *default

  cable:
    <<: *default
